export const ADD_ELEMENT = 'ADD_ELEMENT';
export const ADD_UI_ORDER = 'ADD_UI_ORDER';
export const ADD_WIDGET = 'ADD_WIDGET';
export const REORDER_ELEMENT = 'REORDER_ELEMENT';
export const DELETE_ELEMENT = 'DELETE_ELEMENT';
export const ELEMENT_ERROR = 'ELEMENT_ERROR';